apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticketing
build:
  # Google Cloud Build
  # googleCloudBuild:
  #   projectId: ticketing-com-353405
  artifacts:
    # - image: christseng89/auth
    - image: us.gcr.io/ticketing-com-353405/auth
      context: auth
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*
