apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticketing
build:
  # Google Cloud Build
  # googleCloudBuild:
  #   projectId: ticketing-com-353405
  artifacts:
    - image: christseng89/auth
      # - image: us.gcr.io/ticketing-com-353405/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: christseng89/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: christseng89/tickets
      # - image: us.gcr.io/ticketing-com-353405/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: christseng89/orders
      # - image: us.gcr.io/ticketing-com-353405/orders
      context: orders
      docker:
        dockerfile: Dockerfile
    - image: christseng89/expiration
      # - image: us.gcr.io/ticketing-com-353405/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
    - image: christseng89/payments
      # - image: us.gcr.io/ticketing-com-353405/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
      - infra/k8s-dev/*
