apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: christseng89/auth
      context: auth
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*
