name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'ticketing/k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doct@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      - run: kubectl apply -f ticketing/k8s
