name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'ticketing/client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/client && docker build -t christseng89/ticketing-client . # client image name
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push christseng89/ticketing-client # client image name ###
      - uses: digitalocean/action-doctl@v2 ### revise here...
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      - run: kubectl rollout restart deployment client-depl
