name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - 'ticketing/orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing/orders && docker build -t christseng89/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push christseng89/orders
      - uses: digitalocean/action-doctl@v2 ### revise here...
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      - run: kubectl rollout restart deployment orders-depl
